### ISSUE TITLE
Wrong_Code

### ISSUE THREAD

**Issue by raju442** [JavaDevelopersMccoy/Proj#1]
package com.mccoy;

import java.io.IOException;
import java.io.PrintWriter;
import java.lang.*;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class LoginPage extends HttpServlet {

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		PrintWriter out = response.getWriter();
		
		String usr = request.getParameter("username");
		String pass = request.getParameter("pwd");
		
		if(usr.equals("admin")&& pass.equals("admin"))
			out.println("Login Success..!!!");
			out.println("Login Failed..!!!!");		
}

}

**Comment by HarishChakrasali** [comment]
Else block is missing

**Comment by dinesh-bit** [comment]
flower bracket missing

**Comment by shahabrar435** [comment]
Ok
